---
- name: create directory
  file:
    path: "{{ docker_composefiles_dir }}/zigbee2mqtt/"
    state: directory

- name: create directory
  file:
    path: "{{ zigbee2mqtt_conf_dir }}"
    state: directory

- name: docker-compose file
  template:
    src: templates/zigbee2mqtt/docker-compose.yml.j2
    dest: "{{ docker_composefiles_dir }}/zigbee2mqtt/docker-compose.yml"

- name: enable systemd services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "dc@zigbee2mqtt"
