---
- name: Configure Raspberry Pi 3
  # Call this playbook with --ask-pass
  hosts: all
  gather_facts: yes

  pre_tasks:
  - name: Include secrets
    include_vars:
      file: secrets.yml

  roles:
    - { role: pi3_base, become: yes, become_method: sudo, tags: [base] }
    - { role: pi3_docker, become: yes, become_method: sudo, tags: [docker] }
    - { role: pi3_zigbee2mqtt, become: yes, become_method: sudo, tags: [zigbee2mqtt] }
    - { role: pi3_myconfig, become: yes, become_method: sudo, tags: [myconfig] }
