---
- name: create homeassistant database
  influxdb_database:
      database_name: "{{homeassistant_influx_database}}"

- name: install homeassistant configuration
  template:
    src: templates/homeassistant/configuration.yaml.j2
    dest: "{{ homeassistant_conf_dir }}/configuration.yaml"
  notify:
    - restart home assistant

# TODO addtl files

- name: install zigbee2mqtt configuration
  template:
    src: templates/zigbee2mqtt/configuration.yaml.j2
    dest: "{{ zigbee2mqtt_conf_dir }}/configuration.yaml"
  notify:
    - restart home assistant