---
- name: install zigbee2mqtt configuration
  template:
    src: files/zigbee2mqtt/configuration.yaml
    dest: "{{ zigbee2mqtt_conf_dir }}/configuration.yaml"
  notify:
    - restart home assistant
