---
- name: install/update packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - mosquitto
    - mosquitto-clients
#    - python3-dev
#    - python3-pip
#
#- name: install python mqtt library
#  pip:
#    name: paho-mqtt
#    state: present

- name: enable systemd services
  systemd:
    name: mosquitto.service
    state: started
    enabled: true
