---
# get model:
# cat /proc/device-tree/model
# Raspberry Pi 3 Model B
- name: set the keyboard layout to de on initial setup
  copy:
    src: files/keyboard
    dest: /etc/default/keyboard
  register: keyboard
- name: set the keyboard layout to de on initial setup
  shell: >
    dpkg-reconfigure -f noninteractive keyboard-configuration
    dpkg-reconfigure -f noninteractive console-setup
  when: keyboard.changed

- name: upgrade raspian
  apt:
    upgrade: safe
    autoremove: yes
  notify:
    - reboot pi

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin
  notify:
    - restart cron

#TODO limit to version 3B
- name: disable internal wifi
  lineinfile:
    path: /boot/config.txt
    line: 'dtoverlay=pi3-disable-wifi'
  notify:
    - reboot pi

- name: overclock sd card
  lineinfile:
    path: /boot/config.txt
    line: 'dtparam=sd_overclock=100'
  notify:
    - reboot pi
- name: disable wlan0 power save on boot
  lineinfile:
    path: /etc/rc.local
    insertafter: EOD
    line: '/sbin/iw dev wlan0 set power_save off'

- name: copy wlan settings
  template:
    src: templates/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart networking

- name: install wlan checks
  template:
    src: templates/checkwifi.sh.j2
    dest: /usr/local/bin/checkwifi.sh
    owner: root
    group: root
    mode: 0755

- name: run checkwifi regularly
  cron:
    name: 'checkwifi'
    minute: '*/5'
    job: '/usr/local/bin/checkwifi.sh >> /dev/null 2>&1'

- name: install/update packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - vim
    - python3-dev
    - python3-pip
